# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCayS3jQAH9Xln_vi3FTh8n9cwA3cHdS
"""



import requests
import pandas as pd
import matplotlib.pyplot as plt

# ✅ Step 1: Fetch COVID-19 data
url = "https://disease.sh/v3/covid-19/countries"
data = requests.get(url).json()  # <-- This creates the 'data' variable

# ✅ Step 2: Convert to DataFrame
df = pd.DataFrame(data)

# ✅ Step 3: Get top 10 countries by cases
top10 = df.nlargest(10, 'cases')

# ✅ Step 4: Plot
plt.bar(top10['country'], top10['cases'])
plt.xticks(rotation=45)
plt.title("Top 10 countries by COVID-19 cases")
plt.ylabel("Total Cases")
plt.show()